version: '3.7'
services:
  registry:
    image: registry:2.7
    restart: unless-stopped
    networks:
      - nginx
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - /data/registry:/var/lib/registry

networks:
  nginx:
    external:
      name: nginx
