version: '3.7'
services:
  hysteria:
    image: mritd/hysteria
    container_name: hysteria
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./conf:/etc/hysteria
    command:
      - proxy
      - server
      - -listen
      - ":3000"
      - -auth
      - /etc/hysteria/auth
      - -cert
      - /etc/hysteria/ssl/hysteria.cer
      - -key
      - /etc/hysteria/ssl/hysteria.key
      - -max-conn-client
      - "30000"
      - -obfs
      - bleem
