version: '3.9'
services:
  caddy:
    image: mritd/caddy
    container_name: caddy
    restart: always
    networks:
      - caddy
    environment:
      TZ: Asia/Shanghai
      ACME_EMAIL:
      ACME_ISSUER:
      ACME_ISSUER_PARAMS:
      GANDI_API_TOKEN:
      CLOUDFLARE_API_TOKEN:
      TELEGRAM_DOMAIN:
      TROJAN_DOMAIN:
      TROJAN_PASSWORD:
    volumes:
      - /etc/timezone:/etc/timezone
      - ./conf:/etc/caddy
      - config:/config
      - data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
networks:
  caddy:
    name: caddy
volumes:
  config:
  data:
