version: '3.9'
services:
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone

networks:
  caddy:
    name: caddy
    external: true
