services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    networks:
      caddy:
        ipv4_address: 172.18.0.222
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - conf:/opt/adguardhome/conf
      - data:/opt/adguardhome/work

networks:
  caddy:
    name: caddy
    external: true

volumes:
  conf:
  data:
