version: '3.9'
services:
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/data
    ports:
      - "6379:6379"
    command: ["redis-server","--appendonly","yes"] # "--requirepass", "PASSWORD"
volumes:
  data:

