version: '3.9'
services:
  mritd_com:
    image: mritd/mritd.com
    container_name: mritd_com
    restart: always
    networks:
      - caddy
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone

networks:
  caddy:
    name: caddy
    external: true
